### ISSUE TITLE
react window

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/playwright-tests#10]
1. go to https://react-window.vercel.app/#/examples/list/memoized-list-items
2. select the examples in the examples list

https://www.loom.com/share/b53ddcd91f2643e98693eec1d804b5c9

**Comment by flaurida** [comment]
@ryanjduffy https://github.com/RecordReplay/playwright-tests/blob/main/qawolf/react_window_select_examples_in_list.js
