### ISSUE TITLE
Test natto.dev

### ISSUE THREAD

**Issue by jasonLaster** [RecordReplay/playwright-tests#90]
We should have a test that 

1. goes to https://natto.dev/
2. hovers in the top left and clicks weather
3. clicks run on some of the cells

similar to this replay https://app.replay.io/recording/8a34da01-a7a1-40fe-aac0-34fb2d79e2de?point=6814889627197216239043040440746101&time=3005.21325648415&hasFrames=true

**Comment by flaurida** [comment]
@ryanjduffy https://github.com/RecordReplay/playwright-tests/blob/main/qawolf/natto_navigate_to_weather_run_cell.js
